apiVersion: chaos-mesh.org/v1alpha1
kind: Schedule
metadata:
  name: schedule-dns-chaos-demo 
spec:
  schedule: '* * * * *'
  historyLimit: 2
  concurrencyPolicy: 'Allow'
  type: 'DNSChaos'
  dnsChaos:
    action: error # important: error, no random responses
    mode: all
    patterns:
      - o11y.*
      - cncf.io
      - gitlab.com
      - containerdays.io
      - kubesimplify.com
    selector:
      namespaces:
        - default
    duration: '60s'

